name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker imagedocker run -d -p 80:80 nginx

      run: docker build . --file dockerfile --tag nginx-new
           docker run -d -p 80:80 nginx

      
    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        registry: your-docker-registry
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push Docker image
      run: docker tag nginx:latest ankit1400/nginx-new
           docker push ankit1400/nginx-new



          
